### ISSUE TITLE
REFACTOR TASKS

### ISSUE THREAD

**Issue by asya982** [Team-Alexander/frontend#102]
# Tasks
### STAGE 3
- [x] Перенести запит на пруфи в редакс
- [x] talents.js => gridOfInfo (?) - зробити там запити на таланти та пруфи (санки)
- [x] Зробити відображення дати
- [x] usePagination - кстомний хук для валідаціі пагінації
- [x] API auth- make login and register one function
- [x] Initialization of app
- [x] Add redux to proof
- [x] Винести modalPathname в кастомний хук
- [x] Кнопка пабліш - тіко в едіт моді (форма пруфу)
- [x] Попап меседж зі стейту хай бере та хай десь в еппі лежить завжди
- [x] Прив’язати пруф до роутера і реалізувати пагінацію через юрл
- [x] Зробити скелетон лоадери для пруфів
- [x] Обробити нещодавню дату пруфу ( <a week ago, e.g. 10 min ago)
- [x] ProofPage - save sort in url
- [ ] Під’єднати бібліотеку для локейшену
- [ ] Рефреш токен
- [ ] Обробити фотки : помилки✅, завантаження✅, бакет

### STAGE 4
- [x] Валідація менше символів
- [x] Трім самері та тайтл
- [x] Footer refactor
- [x] Kudos select - make it slider
- [x] Add balance - when overflow max - make it max
- [x] Add top donators on proof page
- [x] Add more text to summary
- [x] Handle my_proof view
- [x] Handle sponsor see how many kudos did he put

### STAGE 5
- [ ] Redesign home page
